### ISSUE TITLE
데이터베이스 마이그레이션

### ISSUE THREAD

**Issue by GBS-Skile** [Team-Crescendo/laravel-central-api#2]
이하는 phpmyadmin으로 mysql DB를 직접 수정한 내역입니다. 마이그레이션 코드 작성해주세요!

* `receipts.points_old`, `receipts.points_new` 자료형 INT(11)에서 BIGINT(20)으로 변경
* `items.expiration_time`, `items.purchase_limit` NOT NULL에서 NULL로 변경
  - 해당 부분은 `database.sql`에는 적혀있었는데 마이그레이션 과정에서 제대로 반영되지 않은 것 같습니다.

**Comment by kdwkr** [comment]
완료된듯
- https://github.com/Team-Crescendo/laravel-central-api/commit/da1c5e337a525e65db59b4b7912d7cf64e79dd88
- https://github.com/Team-Crescendo/laravel-central-api/commit/8a4f09e4daf2b8bb5482fac2534123ee8cfe8712
